kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-watcher
subjects:
  - kind: ServiceAccount
    name: image-watcher
    namespace: image-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-watcher
