kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-watcher
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - images
